export const API = {
  AUTH: '/api/auth',
  AUTH_GOOGLE: '/api/auth/oauth/google',
  ME: '/api/me',
  ACCOUNTS: '/api/admin/accounts',
  ACCOUNTS_SUPERADMIN: '/api/superadmin/accounts',
  DONATION_PROGRAMS: '/api/donation-programs',
  DONATION_PROGRAMS_ADMIN: '/api/admin/donation-programs',
  FOSTER_CHILDREN: '/api/foster-children',
  FOSTER_CHILDREN_ADMIN: '/api/admin/foster-children',
  SOCIAL_PROGRAMS: '/api/social-programs',
  SOCIAL_PROGRAMS_ADMIN: '/api/admin/social-programs',
  FINANCE_RECORD: '/api/finance-records',
  GALLERIES: '/api/galleries',
  GALLERIES_ADMIN: '/api/admin/galleries',
  NEWS: '/api/news',
  NEWS_ADMIN: '/api/admin/news',
  AMBULANCES: '/api/ambulances',
  AMBULANCES_ADMIN: '/api/admin/ambulances',
  FOUNDATION_PROFILE: '/api/foundation-profile',
  FOUNDATION_PROFILE_ADMIN: '/api/admin/foundation-profile',
}
