export const API = {
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REGISTER: '/api/auth/register',
  AUTH_VERIFY_EMAIL: '/api/auth/verify-email',
  AUTH_RESEND_VERIFICATION: '/api/auth/resend-verification',
  AUTH_FORGET_PASSWORD: '/api/auth/forget-password',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_GOOGLE: '/api/auth/oauth/google',
  CURRENT_USER: '/api/me',
  CURRENT_USER_PASSWORD: '/api/me/password',
  USERS: '/api/users',
  ROLES: '/api/public/users/roles',
  DONATIONS: '/api/donations',
  DONATIONS_PUBLIC: '/api/public/donations',
  DONATION_TRANSACTION: '/api/donation-transactions',
  DONATION_TRANSACTION_PUBLIC: '/api/public/donation-transactions',
  CHILDREN: '/api/children',
  CHILDREN_PUBLIC: '/api/public/children',
}
